### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by flippette** [HanoiMUN/hmun-web#1]
- [x] common elements (top navbar and footer)
- [x] landing page (16/3)
  - [x] working countdown (6/3)
  - [x] reg form (16/3)
    - [x] ui (14/3)
    - [x] ~~gsuite integration (16/3)~~ we use jotform now
- [x] about section (16/3)
- [x] ~~sponsor &~~ contacts section (16/3)
- [x] preview & polish (18/3)
- [x] migrate to [the main domain](https://hanoimun.org) (19/3)
- [x] general availability (20/3)
